const Images = {
    firstSlider: new URL('./firstSlider.webp', import.meta.url).href,
    secondSlider: new URL('./secondSlider.jpg', import.meta.url).href,
    thirdSlider: new URL('./thirdSlider.avif', import.meta.url).href,
    fourthSlider: new URL('./fourthSlider.jpg', import.meta.url).href,
    logo: new URL('./logo.png', import.meta.url).href,
    aravali: new URL('./aravali.webp', import.meta.url).href,
    closing: new URL('./colosing.avif', import.meta.url).href,
    old_olympic: new URL('./old-olympic.avif', import.meta.url).href,
    aman: new URL('./Aman AMAN.avif', import.meta.url).href,
    harmanpreet: new URL('./Harmanpreet.jpeg', import.meta.url).href,
    esha: new URL('./Esha Singh.jpeg', import.meta.url).href,
    manu: new URL('./Manu BHAKER.jpg', import.meta.url).href,
    neeraj: new URL('./neeraj.avif', import.meta.url).href,
    swapnil: new URL('./Swapnil KUSALE.webp', import.meta.url).href,
    olympic_flag: new URL('./Olympic_flag.jpg', import.meta.url).href,
    neeraj_asian: new URL('./neeraj_asian.webp', import.meta.url).href,
    neeraj_winning: new URL('./neeraj_winning.avif', import.meta.url).href,
    neeraj_training: new URL('./neeraj_training.jpg', import.meta.url).href,
    harmanpreet_action: new URL('./harmanpreet_action.jpeg', import.meta.url).href,
    harmanpreet_tokyo: new URL('./harmanpreet_tokyo.jpeg', import.meta.url).href,
    swapnil_shooting: new URL('./swapnil_shooting.jpg', import.meta.url).href,
    swanil_achive: new URL('./swanil_achive.jpg', import.meta.url).href,
    anman_wrestling: new URL('./anman_wrestling.avif', import.meta.url).href,
    aman_ahciev: new URL('./aman_ahciev.jpeg', import.meta.url).href,
    esha_shooting: new URL('./esha_shooting.avif', import.meta.url).href,
    esha_achiev: new URL('./esha_achiev.avif', import.meta.url).href,
    manu_shooting: new URL('./manu_shooting.avif', import.meta.url).href,
    manu_achiev: new URL('./manu_achiev.avif', import.meta.url).href,
}

export {Images}